storage:
  image: busybox
  volumes:
      - /var/lib/postgresql/data
db:
  image: postgres:9.6.1
  environment:
    POSTGRES_USER: preview_book
    POSTGRES_PASSWORD: preview_book
  ports:
    - "5432:5432"
  volumes_from:
      - storage
